# SPDX-FileCopyrightText: 2025 Michał Górny, 2021 The meson-python developers
# SPDX-License-Identifier: MIT

from __future__ import annotations

import importlib.metadata
import subprocess
import sys
import sysconfig
import warnings
from pathlib import Path
from venv import EnvBuilder

import packaging.version
import pytest

from typing import Generator


TOP_DIR = Path(__file__).parent.parent
TEST_CASES = [
    "meson-python/c",
    "scikit-build-core/c",
    "setuptools/c",
    "meson-python/cython",
    "scikit-build-core/cython",
    "setuptools/cython",
]


@pytest.fixture(scope="session", params=TEST_CASES)
def test_case(request: pytest.Request) -> Generator[Path]:
    yield TOP_DIR / request.param


class VEnv(EnvBuilder):
    def __init__(self, env_dir):
        super().__init__(symlinks=True, with_pip=True)

        # This warning is mistakenly generated by CPython 3.11.0
        # https://github.com/python/cpython/pull/98743
        with warnings.catch_warnings():
            if sys.version_info[:3] == (3, 11, 0):
                warnings.filterwarnings(
                    "ignore",
                    "check_home argument is deprecated and ignored.",
                    DeprecationWarning,
                )
            self.create(env_dir)

        # Free-threaded Python 3.13 requires pip 24.1b1 or later.
        if sysconfig.get_config_var("Py_GIL_DISABLED"):
            if packaging.version.Version(
                importlib.metadata.version("pip")
            ) < packaging.version.Version("24.1b1"):
                self.pip("install", "--upgrade", "pip >= 24.1b1")

    def ensure_directories(self, env_dir):
        context = super().ensure_directories(env_dir)
        # Store the path to the venv Python interpreter. There does
        # not seem to be a way to do this without subclassing.
        self.executable = context.env_exe
        return context

    def python(self, *args: str):
        return subprocess.check_output([self.executable, *args]).decode()

    def pip(self, *args: str):
        return self.python("-m", "pip", *args)


@pytest.fixture()
def venv(tmp_path_factory) -> VEnv:
    path = Path(tmp_path_factory.mktemp("mesonpy-test-venv"))
    return VEnv(path)
